 python3 load_legacy_objects.py -v 2.0.1  -m full
 python3 load_legacy_objects.py -v 1.12.3  -m full
 python3 load_legacy_objects.py -v 1.11.2  -m full
 python3 load_legacy_objects.py -v 1.10.6  -m full
 python3 load_legacy_objects.py -v 1.9.9  -m full
 python3 load_legacy_objects.py -v 1.8.25  -m full
 python3 load_legacy_objects.py -v 1.8.24  -m full
 python3 load_legacy_objects.py -v 1.7.13  -m full
 python3 load_legacy_objects.py -v 1.7.10  -m full
 python3 load_legacy_objects.py -v 1.5.36  -m full
 python3 load_legacy_objects.py -v 1.5.30  -m full
 python3 load_legacy_objects.py -v 1.5.28  -m full
 python3 load_legacy_objects.py -v 1.5.27  -m full
 python3 load_legacy_objects.py -v 1.5.23  -m full
 python3 load_legacy_objects.py -v 1.5.18  -m full
 python3 load_legacy_objects.py -v 1.5.13  -m full
 python3 load_legacy_objects.py -v 1.5.12  -m full
 python3 load_legacy_objects.py -v 1.5.11  -m full
 python3 load_legacy_objects.py -v 1.4.5  -m full
 python3 load_legacy_objects.py -v 1.0.13  -m full
